# Generated by Django 3.2.9 on 2021-11-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('release_date', models.DateField(verbose_name='Дата выпуска')),
                ('lte_exist', models.CharField(max_length=3, verbose_name='Наличие LTE')),
                ('slug', models.SlugField(verbose_name='Slug')),
            ],
        ),
    ]
